name: Preview Terraform Plan

on:
  pull_request:

jobs:
  preview:
    name: Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Terramate install
        run: go install github.com/terramate-io/terramate/cmd/...@latest

      - name: Terramate List changed stacks
        id: list
        run: |
          echo "stdout<<STDOUT" >>$GITHUB_OUTPUT
          terramate list --changed >>$GITHUB_OUTPUT
          echo "STDOUT" >>$GITHUB_OUTPUT

      # If there is any changes made then only the below pipeline will execute, Otherwise nothing will happen

      - name: Configure AWS Credentials
        if: steps.list.outputs.stdout
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Create Terraform plan on changed stacks
        if: steps.list.outputs.stdout
        run: |
          terramate run --changed -- terraform init
          terramate run --changed -- terraform validate
          terramate run --changed -- terraform plan -out out.tfplan

      - name: Preview Comment For Admin
        if: steps.list.outputs.stdout
        run: |
          terramate run --changed -- terraform show -no-color out.tfplan

      - name: Inform about no Changed Stacks
        if: (!steps.list.outputs.stdout)
        run: |
          echo "### No changed stacks."
